[job]
task       = "vfm"
experiment = "egoverse_joint_video_hand_pose_overfit_v0_6_frame_delta_temporal_mask"
project    = "joint_video_hand_pose"
group      = "overfit"
name       = "overfit_v0.6_frame_delta_temporal_mask"
wandb_mode = "online"

[model]
precision = "bfloat16"

[model.parallelism]
data_parallel_shard_degree     = 8
data_parallel_replicate_degree = 1
context_parallel_shard_degree  = 1

[model.activation_checkpointing]
mode = "full"

[model.compile]
enabled = false

[optimizer]
lr = 2.0e-5

[scheduler]
warm_up_steps = [100]
cycle_lengths = [1200]
f_start       = [0.0]
f_max         = [1.0]
f_min         = [0.1]

[trainer]
max_iter     = 1200
logging_iter = 1

[checkpoint]
load_path = "${oc.env:BASE_CHECKPOINT_PATH,/mnt/checkpoints/Cosmos3-Nano-dcp-sft/iter_000048464}"
save_iter = 300
